---
alerters:
  email:
    sender: xiao.ming.track@gmail.com
    recipients:
      - xiao.ming.track@gmail.com
      - yubenoit@email.com
    relay: 127.0.0.1
    password: callmexiaoming!   # optional
...