---
refresh_interval: 2 # seconds
max_price: 750 # dollars
urls:
  - https://www.amazon.fr/PlayStation-%C3%89dition-Standard-DualSense-Couleur/dp/B08H93ZRK9
  - https://www.amazon.fr/PlayStation-Digital-Manette-DualSense-Couleur/dp/B08H98GVK8
  - https://www.amazon.fr/Orzly-Duocharger-PS5-Manette-Chargeur/dp/B08MCJ5YQY
...
